In [1]:
# -*- coding: utf-8 -*-
"""
CellStrat
"""

#==============================================================================
# First step to write the python program is to take benefit out of libraries
# already available. We will only focus on the data science related libraries.
#==============================================================================

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#==============================================================================
# #import data from the data file. In our case its Health.csv. 
#==============================================================================

healthData = pd.read_csv ('Health.csv')
print(healthData)

  Ethnicity  Height (CM)  Weight (Kg) Will survive till 70
0     White        186.0         90.0                  Yes
1   African        185.0         98.0                   No
2     White        175.0         80.0                   No
3     White        180.0         88.0                  Yes
4     Asian        178.0          NaN                   No
5     Asian        172.0         72.0                  Yes
6   African        178.0         75.0                   No
7     White          NaN         89.0                  Yes
8   African        186.0         90.0                  Yes


In [2]:
#==============================================================================
# All mathematical operations will be performed on the matrix, so now we create
# matrix for dependent variables and independent variables.
#==============================================================================


X = healthData.iloc [:,:-1].values
y = healthData.iloc [:,3].values

X

array([['White', 186.0, 90.0],
       ['African', 185.0, 98.0],
       ['White', 175.0, 80.0],
       ['White', 180.0, 88.0],
       ['Asian', 178.0, nan],
       ['Asian', 172.0, 72.0],
       ['African', 178.0, 75.0],
       ['White', nan, 89.0],
       ['African', 186.0, 90.0]], dtype=object)

In [3]:
y

array(['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes'],
      dtype=object)

In [4]:
#==============================================================================
# Handle the missing values, we can see that in dataset there are some missing
# values, we will use strategy to impute mean of column values in these places
#==============================================================================

from sklearn.preprocessing import Imputer
# First create an Imputer
missingValueImputer = Imputer (missing_values = 'NaN', strategy = 'median',axis = 0)
# Set which columns imputer should perform
missingValueImputer = missingValueImputer.fit (X[:,1:3])
# update values of X with new values
X[:,1:3] = missingValueImputer.transform(X[:,1:3])

print(X)

[['White' 186.0 90.0]
 ['African' 185.0 98.0]
 ['White' 175.0 80.0]
 ['White' 180.0 88.0]
 ['Asian' 178.0 88.5]
 ['Asian' 172.0 72.0]
 ['African' 178.0 75.0]
 ['White' 179.0 89.0]
 ['African' 186.0 90.0]]


C:\Users\amare\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [5]:
#==============================================================================
# Encode the categorial data. So now instead of character values we will have
# corresponding numerical values
#==============================================================================

from sklearn.preprocessing import LabelEncoder
# X_labelencoder =
X[:,0] =  LabelEncoder().fit_transform(X[:, 0])
print (X)

[[2 186.0 90.0]
 [0 185.0 98.0]
 [2 175.0 80.0]
 [2 180.0 88.0]
 [1 178.0 88.5]
 [1 172.0 72.0]
 [0 178.0 75.0]
 [2 179.0 89.0]
 [0 186.0 90.0]]


In [6]:
# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

[1 0 0 1 0 1 0 1 1]


In [7]:
#==============================================================================
# Implementing OneHotEncoder to separate category variables into dummy 
# variables.
#==============================================================================

from sklearn.preprocessing import OneHotEncoder
X_onehotencoder = OneHotEncoder (categorical_features = [0])
X = X_onehotencoder.fit_transform(X).toarray()
print (X)

[[  0.    0.    1.  186.   90. ]
 [  1.    0.    0.  185.   98. ]
 [  0.    0.    1.  175.   80. ]
 [  0.    0.    1.  180.   88. ]
 [  0.    1.    0.  178.   88.5]
 [  0.    1.    0.  172.   72. ]
 [  1.    0.    0.  178.   75. ]
 [  0.    0.    1.  179.   89. ]
 [  1.    0.    0.  186.   90. ]]


C:\Users\amare\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\amare\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
#==============================================================================
# split the dataset into training and test set. We will use 80/20 approach
#==============================================================================

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.3,
                                                     random_state = 0)

In [17]:
#==============================================================================
# Feature scaling is to bring all the independent variables in a dataset into
# same scale, to avoid any variable dominating  the model. Here we will not 
# transform the dependent variables.
#==============================================================================

from sklearn.preprocessing import StandardScaler
independent_scalar = StandardScaler()
X_train = independent_scalar.fit_transform (X_train) #fit and transform
X_test = independent_scalar.transform (X_test) # only transform
print(X_train)

[[-0.70710678  1.41421356 -0.70710678 -0.40824829  0.61503402]
 [ 1.41421356 -0.70710678 -0.70710678  1.22474487  0.81631789]
 [ 1.41421356 -0.70710678 -0.70710678 -0.40824829 -1.19652074]
 [-0.70710678 -0.70710678  1.41421356  0.          0.5479394 ]
 [-0.70710678 -0.70710678  1.41421356  1.22474487  0.81631789]
 [-0.70710678  1.41421356 -0.70710678 -1.63299316 -1.59908846]]
